# Generated by Django 3.0.4 on 2020-04-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(default='company address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(default='Almaty', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default='company description'),
        ),
    ]
