# Generated by Django 3.0.4 on 2020-03-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
